//
// Created by mrfarinq on 10.05.17.
//

#ifndef UNTITLED_GRAPHADJACENCYLISTSIMPLEMENTATION_H
#define UNTITLED_GRAPHADJACENCYLISTSIMPLEMENTATION_H


class GraphAdjacencyListsImplementation {

};


#endif //UNTITLED_GRAPHADJACENCYLISTSIMPLEMENTATION_H
